### ISSUE TITLE
Triage permission level to apply labels to issues

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-services#4]
I can't apply labels to issues in the rhasspy organization. It would be nice if @mathquis and I could label issues to help manage them and add visuals in our project boards. Apparently we need the [Triage](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) permission level to do this. Does that look sensible to you, @synesthesiam, to upgrade our permission level?

**Comment by synesthesiam** [comment]
I've tried switching both of you to having Write permission. Does this allow you to modify issues?

**Comment by koenvervloesem** [comment]
That works, thanks!
